logging:
  config: classpath:log4j2.properties
  level:
    com.gin: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${databse.name}?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: lzbx2837200
server:
  port: 8089