logging:
  config: classpath:log4j2.properties
  level:
    com.gin: info

spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/${databse.name}?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: lzbx2837200
